// <auto-generated />
namespace LocalServer.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dispatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dispatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201312082303557_dispatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
