// <auto-generated />
namespace LocalServer.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2));
        
        string IMigrationMetadata.Id
        {
            get { return "201310261110285_init2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
