// <auto-generated />
namespace LocalServer.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class session : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(session));
        
        string IMigrationMetadata.Id
        {
            get { return "201312031705023_session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
