// <auto-generated />
namespace LocalServer.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class presicion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(presicion));
        
        string IMigrationMetadata.Id
        {
            get { return "201312060549108_presicion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
