// <auto-generated />
namespace LocalServer.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class notifs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notifs));
        
        string IMigrationMetadata.Id
        {
            get { return "201312090141142_notifs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
